<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Nullable>disable</Nullable>
    <AssemblyName>FormFlux</AssemblyName>
    <RootNamespace>FormFlux</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>FormFlux</AssemblyTitle>
    <Product>FormFlux</Product>
    <Description>Grasshopper plugin for generative parcel massing with multiple building typologies</Description>
    <Copyright>Copyright © 2025</Copyright>
    <Version>1.0.0</Version>
    <TargetExt>.gha</TargetExt>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="7.13.21348.13001" />
    <PackageReference Include="RhinoCommon" Version="7.13.21348.13001" />
    <PackageReference Include="System.Resources.Extensions" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icons\FormFlux.png" />
    <EmbeddedResource Include="Icons\FluxTemplate.png" />
    <EmbeddedResource Include="Icons\FluxTree.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Templates\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
