name: Yak Release

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/_package.yml
    with:
      channel: release
      publish: true
    secrets:
      YAK_TOKEN: ${{ secrets.YAK_TOKEN_PATRICK }}
